import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import { gql } from "@apollo/client";

import client from "../utils/apollo-client";

export async function getStaticProps() {
  const { data } = await client.query({
    query: gql`
      query Countries {
        countries {
          code
          name
          emoji
        }
      }
    `,
  });

  return {
    props: {
      countries: data.countries.slice(0, 4),
    },
  };
}

const Home: NextPage = ({}) => {
  return (
    <div>
      <Head>
        <title>EGO Lounge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main></main>
    </div>
  );
};

export default Home;
